config/default.example.yml, lib/mcs-core/lib/adapters/freeswitch/freeswitch.js, lib/mcs-core/lib/model/media-session.js, lib/mcs-core/lib/model/media.js, lib/mcs-core/lib/model/sdp-media.js, lib/mcs-core/lib/model/sdp-session.js, lib/mcs-core/lib/model/user.js, lib/mcs-core/lib/utils/sdp-wrapper.js
- Added OPUS specs to better match the listen only subscribers from the browser with the FreeSWITCH parameters. This should improve overall listen only audio quality. The values in `default.example.yml` should be altered to match the ones configured on FreeSWITCH. The values in this PR correspond to the ones present in BBB's 2.2/FS 1.8.2 version.
- Fixed audio stream accounting in mcs-core's balancer
- Fixed an issue where the RTP converter from listen only streams would be incorrectly released when the FS adapter was also used for full audio streams.
=> Listen only and full audio spec codec and fixes

config/client_secret.example.json, config/custom-environment-variables.yml, config/default.example.yml, lib/bbb/messages/Constants.js, lib/bbb/messages/Messaging.js, lib/bbb/messages/stream/StreamOAuth2DataMessage.js, lib/bbb/messages/stream/StreamOAuth2UrlMessage.js, lib/oauth2/server.js, lib/stream/StreamManager.js, lib/stream/containers/docker.js, lib/stream/containers/kubernetes.js, lib/stream/stream.js, package-lock.json, package.json
Replaces #4.
CHANGELOG:
- Added support for streaming with authentication via OAuth2 (@lfzawacki). 
```
This could be extended to other streaming providers that can log you via OAuth2, 
but for now it works with the Google API to get data from the users youtube account. 
Here's a private gist with configuration instructions: 
https://gist.github.com/lfzawacki/c24f6b073754644d36b9ad73e2306fb5
```
- Disabled the `streaming` module by default and included a custom env var to specify the modules which the component should start (`SFU_PROCESS`)
=> Version 2.2.4 with OAuth2/Streaming

lib/base/MCSAPIWrapper.js, lib/mcs-core/lib/media/mcs-message-router.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/model/media-session.js, lib/mcs-core/lib/model/media.js, lib/mcs-core/lib/model/room.js, lib/mcs-core/lib/model/sdp-media.js, lib/mcs-core/lib/model/sdp-session.js, lib/mcs-core/lib/utils/sdp-wrapper.js, lib/screenshare/screenshare.js, package-lock.json, package.json
- Follow the changes done on https://github.com/mconftec/mcs-js/pull/11. I did this to facilitate client usage of the floor methods and floor tracking on their sides without having to keep state. Also standardized the way the floor methods were used and parameterized and we now provide a way to safely detect when there's no more content in the room;
- Fixed an issue while parsing for content SDPs;
- Correctly fill the content media type and decouple it from application (now unused);
- Bump mcs-js version to v0.0.4-dev.
=> Implemented the changes done in the mcs-core API's floor methods

lib/base/MCSAPIWrapper.js, lib/bbb/messages/Constants.js, lib/mcs-core/lib/adapters/freeswitch/freeswitch.js, lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/media/mcs-message-router.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/model/media-session.js, lib/mcs-core/lib/model/media.js, lib/mcs-core/lib/model/room.js, lib/mcs-core/lib/model/sdp-media.js, lib/mcs-core/lib/model/sdp-session.js, lib/mcs-core/lib/model/user.js, lib/mcs-core/lib/utils/sdp-wrapper.js, lib/screenshare/ScreenshareManager.js, lib/screenshare/screenshare.js, lib/video/video.js, package-lock.json, package.json
*CHANGELOG*:
* Version numbers now adhere to semantic versioning, hence the bump to 2.3.0;
* Bump `mcs-js` dep to the `0.0.5` release;
* Refactored the whole content/conference floor to follow the API changes and provide previous floor infos to API consumers. Also made it consistently answer either `MediaSession` or `Media` info objects;
* Reworked the `getMediaPipeline` and `transposeAndConnect` logic in the `kurento` adapter to avoid using `Kue` as a dependency due to race conditions. `Kue` is now removed from the app, reducing its size, and the race condition was natively fixed;
* Fixed an issue with the `connect`/`disconnect` type param comparison in `MediaSession` and `Media` which made some specific calls no-op. The `type` param implementation will be revisited in future version …
=> Version 2.3.0

.gitignore, lib/mcs-core/lib/adapters/freeswitch/freeswitch.js, lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/media/mcs-message-router.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/model/media-session.js, lib/mcs-core/lib/model/media.js, lib/mcs-core/lib/model/sdp-session.js, lib/mcs-core/lib/utils/sdp-wrapper.js, lib/screenshare/ScreenshareManager.js
* Hardened the FreeSWITCH adapter `connect` method error handling
* General improvements to some trace loggings throughout the code
* Some cleanup on deprecated `subscribedSessions` code
* Added extra checks in the kurento adapter for when the pipeline was already released
* Fix regression on MEDIA_NO_AVAILABLE_CODEC error triggering
- Also improved the procedures to filter SDPs by codec and made the processing of SDPs with no specific media lines (lacking audio, video) more natural and resilient
=> Closing v2.3.2

lib/audio/AudioManager.js, lib/audio/AudioProcess.js, lib/audio/audio.js, lib/base/MCSAPIWrapper.js, lib/bbb/messages/Constants.js, lib/bbb/pubsub/bbb-gw.js, lib/mcs-core/lib/media/mcs-message-router.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/model/user.js, lib/screenshare/ScreenshareManager.js, lib/screenshare/screenshare.js, lib/video/VideoManager.js, lib/video/video.js
- BBB and MCS users now have a 1:1 ratio
- Users are automatically started when a BBB user first uses any of the media functionalities (audio, video, screenshare or listen only)
- Users are ejected when the BBB users leaves
- Map the BBB user's name to the MCS user
- Map the BBB user's `intId` to the MCS user's `userId`
- Fixed the `unpublish` API method implementation
=> Map MCS and BBB users 1:1 

lib/mcs-core/lib/media/mcs-message-router.js, package-lock.json, package.json
Patch release 2.3.9.
__CHANGELOG__
* Fixed an issue in mcs-core's client-event map removal procedure which would remove events that it wasn't supposed to.
* Update `js-yaml` dependency (vulnerability)
* Update `@kubernetes/client-node` (vulnerability)
=> Version 2.3.9

Dockerfile
We added a sip.js fork which needs a npm postinstall script. Added the unsafe-perm opt to the Dockerfile so it can build the image correctly.
=> Modify dockerfile to make it work with the new postinstall script

lib/mcs-core/lib/adapters/freeswitch/freeswitch.js
Not proud of it, but FreeSWITCH has a bug where it doesn't end properly the SIP session initiated without SDP when enable-3pcc=proxy is set in its config. So I did what needed to be done.
=> Fixed hangup detection of FS sessions when we act as offerer

lib/mcs-core/lib/utils/base-process.js, lib/mcs-core/process.js
Addresses #54. mcs-core's process shouldn't hang anymore).
The base-process duplication is needed to avoid coupling things even more.
=> Spoof upper layer process class and use it in mcs-core (#54)

config/custom-environment-variables.yml, config/default.example.yml, lib/base/BaseProvider.js, lib/base/MCSAPIWrapper.js, lib/bbb/messages/Constants.js, lib/mcs-core/lib/adapters/freeswitch/freeswitch.js, lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/constants/constants.js, lib/mcs-core/lib/media/mcs-message-router.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/model/media-session.js, lib/mcs-core/lib/model/media.js, lib/mcs-core/lib/model/recording-session.js, lib/mcs-core/lib/model/sdp-media.js, lib/mcs-core/lib/model/sdp-session.js, lib/mcs-core/lib/model/user.js, lib/mcs-core/lib/utils/sdp-wrapper.js, lib/screenshare/screenshare.js, lib/video/video.js, package-lock.json, package.json
Patch release v2.4.2.
__CHANGELOG__
* Improved logging (`c95fa36`)
* Use the optional parameters from the `startRecording` API call (`c95fa36`)
* Add a subscriber media spec slave mode (`5ec3f46`, `d7e32f8`)
- If this is enabled, medias created by the `subscribe` call will inherit the `mediaSpec` from the source media
- Two new configuration options: `videoSubscriberSpecSlave` (env `VIDEO_SUBSCRIBER_SLAVE`),  `screenshareSubscriberSpecSlave` (env `SCREENSHARE_SUBSCRIBER_SLAVE`)
- Disabled by default
* Correctly handle internal SIP re-INVITEs in the FreeSWITCH adapter (`f7cbefe`)
=> Version v2.4.2

lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/media/mcs-message-router.js
Also fixed a quirk with kurento's adapter `generateOffer` pre-filters leaving blank lines in the SDP.
=> Performance experiments with client-event map and leak fixes

config/default.example.yml, lib/audio/audio.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/model/room.js, lib/mcs-core/lib/model/user.js, lib/screenshare/screenshare.js, lib/video/video.js
Implements #123.
- Audio and recording medias are ignored in the threshold accounting for now (`ignoreThresholds: true` optional parameter).
- Unlimited by default.
- The limits are content type agnostic.
Also took the time to fix a small leak in `Room`'s media unit removal.
=> Implement media thresholds (#123)

lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/model/sdp-session.js, lib/mcs-core/lib/utils/sdp-wrapper.js, lib/mcs-core/lib/utils/util.js
- Stack traces are now properly logged in the error handlers with the `error` log level and just once.
- `SdpWrapper#removeSessionDescription` method made static
=> [mcs-core] Properly log stack traces, make removeSessionDescription static

lib/mcs-core/lib/adapters/freeswitch/freeswitch.js, lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/constants/constants.js, lib/mcs-core/lib/model/int-unsupported-media.js, lib/mcs-core/lib/model/media-session.js, lib/mcs-core/lib/model/media.js, lib/mcs-core/lib/model/sdp-session.js, lib/mcs-core/lib/model/user.js, lib/mcs-core/lib/utils/sdp-wrapper.js, package-lock.json, package.json
Closes #139.
Also:
- Bump `sdp-transform` to 2.13.0
- Improve some errors logs in mcs-core#`User`
- [freeswitch] Encode URI before setting it in the UA 
- Workaround: also emit `MEDIA_DISCONNECTED` for the media session when a child media unit gets disconnected.
=> Addresses #139

config/custom-environment-variables.yml, config/default.example.yml, lib/bbb/messages/OutMessage2x.js
Closes #151 and put it behind a configuration option.
New configs:
-  `addTimestampToAkkaMessages`. Environment variable: `AKKA_MSG_TIMESTAMP`
=> Closes #151

config/custom-environment-variables.yml, config/default.example.yml, lib/bbb/messages/OutMessage2x.js
Merge with patch release 2.4.5.
__CHANGELOG__:
- Addressed https://github.com/mconf/bbb-webrtc-sfu/issues/151
* Timestamps in akka-apps message envelopes are enabled by default. Can be controlled by `addTimestampToAkkaMessages` (config) or  `AKKA_MSG_TIMESTAMP` (environment variable).
=> Merge with 2.4.5

lib/video/video.js
VideoManager`s index is not used for it anymore. Timestamp still appended, will differentiante stuff.
Closes #168.
=> Make webcam/video recording name depend only on BBB`s userId (#1

config/default.example.yml, lib/audio/AudioManager.js, lib/audio/audio.js, lib/bbb/messages/Constants.js, lib/mcs-core/lib/media/mcs-message-router.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/model/user.js, lib/screenshare/ScreenshareManager.js, lib/screenshare/screenshare.js, lib/video/VideoManager.js, lib/video/video.js, package-lock.json, package.json
- Revert the user tether added in #121 in favour of a configurable duplicate externalUserId approach
- Added autoLeave optional parameter to mcs-core`s join
- Re-sanitize all leave procedures on video/screenshare/audio and use autoLeave and externalUserId
- Properly rollback media process failures in mcs-core
- Handle stop while starting glare in audio/video providers
- Some scattered log improvements
=> [lt246-3] Load testing follow up #3 for v2.4.6 and close release

config/default.example.yml
This makes H264 video playback working again in Firefox
=> Update H264 video configuration

lib/mcs-core/lib/media/mcs-message-router.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/model/room.js, lib/mcs-core/lib/model/user.js, package-lock.json, package.json
As defined in: https://github.com/mconf/mcs-js/commit/81189f98422825ef9f352433b8df0f6850b4b35b
`getMedias` accepts `memberType` (`room`|`user`|`mediaSession`|`medias`) and `identifier` (the unique internal ID for the identifier) as obligatory parameters and return an array of `mediaSession` or `media` info objects.
It has an optional parameter object (`options`) with two implemented parameters:
- `types`: internal media types to filter in the return value (`[ RTP|WebRTC|RECORDING|URI ]`)
- `mediaTypes`: a `mediaTypes` dictionary with the media types and media directions to filter in the return value.
=> Implement getMedias API call

lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/constants/constants.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/media/media-factory.js, lib/mcs-core/lib/model/filter-session.js, lib/mcs-core/lib/model/room.js
Content video in RTP Sessions are now limited to output 1280x720 pixels
Web/WEBRTC users's still send/receive your content stream without video scaling
A small refactoring in kurento adapter, changing mediaFilter's name to hubPortMediafilter, once these functions are specific for hubports
=> Update video scale for content medias in RTP Sessions

lib/video/VideoManager.js, lib/video/video.js
Changes:
- Backport #169
- [video] Change external video source indexing to be based on the raw stream name. This follows some changes made to the video-provider in order to support multiple cameras.
=> Backport #169 and adjust external video sources indexing

config/custom-environment-variables.yml
Boolean environment variables were being parsed as strings. No good.
Affected variables:
- FS_HANDLE_EXT_CONN
- RECORD_WEBCAMS
- RECORD_SCREENSHARE
- VIDEO_SUBSCRIBER_SLAVE
- SCREENSHARE_SUBSCRIBER_SLAVE
- AKKA_MSG_TIMESTAMP
=> Fix botched boolean environment vars parsing

config/custom-environment-variables.yml, config/default.example.yml, lib/mcs-core/lib/utils/logger.js, lib/utils/Logger.js, package-lock.json, package.json
- Removes the built-in log rotation (in favour of external methods ie logrotate + cron).
- Removes the `winston-daily-rotate-file` dependecy.
Ref #27.
=> Remove built-in log rotation

lib/audio/audio.js
During the stop procedure sanitizing and log refactor in the audio provider I messed up with the notFlowing/flowing handlers and mixed them up.
=> Fix listen only not flowing timeout handling

lib/audio/audio.js
This should avoid a race condition. When a session was stopped before the media trigger cleared the timeouts, they would cause a leak and/or incorrectly trigger a trailing timeout on a probable successful re-connection.
=> [audio] Clear mediaFlowing/State timeouts on stop

lib/base/MCSAPIWrapper.js, lib/bbb/messages/Constants.js, lib/bbb/messages/Messaging.js, lib/bbb/messages/screenshare/ScreenshareRTMPBroadcastStartedEventMessage2x.js, lib/mcs-core/lib/model/sdp-session.js, lib/mcs-core/lib/utils/sdp-wrapper.js, lib/screenshare/ScreenshareManager.js, lib/screenshare/screenshare.js
- Replaces #251.
- [mcs-core]: fixes audio+video bundling for monoadapter calls.
- [screenshare]: adds backwards-compatible support for screenshare bundled with audio.
=> Screenshare with audio, ... (replaces #251)

lib/video/video.js
Video ejection on media timeout (server side) was broken due to a typo in the ejection message parameters.
=> [video] Fix server-side video eject on media timeout

lib/screenshare/screenshare.js
By forcing `mediaProfile: 'content'` in the recording media session creation, we specifically bind it to the `content` type media server if MEDIA_TYPE is being used and the content media unit has bundled audio+video.
Otherwise, the mediaType parsing code would make the recorder endpoint go to the audio type media server, causing a weird VP8 -> H.264 -> VP8 transcoding when bridging the media between servers for recording. The transposing code is still experimental and bound to H.264.
=> [screenshare] Force mediaProfile on recording to avoid transcoding

Dockerfile, package-lock.json, package.json
- Default Docker image Node.js is now 14 (going LTS by the end of the week);
- Bump winston to 2.4.5
- Bump ws to 7.3.1
=> Node.js 14 (Docker), bump Winston and WS

lib/audio/AudioManager.js, lib/audio/audio.js, lib/base/BaseManager.js, lib/base/errors.js, lib/bbb/messages/Constants.js, lib/bbb/messages/Messaging.js, lib/bbb/messages/audio/GetGlobalAudioPermissionReqMsg.js, lib/bbb/messages/screenshare/GetScreenBroadcastPermissionReqMsg.js, lib/bbb/messages/screenshare/GetScreenSubscribePermissionReqMsg.js, lib/bbb/messages/video/GetCamBroadcastPermissionReqMsg.js, lib/bbb/messages/video/GetCamSubscribePermissionReqMsg.js, lib/bbb/pubsub/bbb-gw.js, lib/screenshare/ScreenshareManager.js, lib/screenshare/screenshare.js, lib/video/video.js
- Implement media permission probes used with akka-apps:
* GetGlobalAudioPermissionReqMsg, GetCamBroadcastPermissionReqMsg, GetCamSubscribePermissionReqMsg, GetScreenBroadcastPermissionReqMsg, GetScreenSubscribePermissionReqMsg and its responses
- Improve user left and meeting end cleanup routines
* Listen only users are now properly ejected on 2.x user exits
* Video sessions are now properly cleaned up on 2.x meeting ends, user exits
* Screen sharing sessions are now properly cleaned up on 2.x meeting ends, user exits
=> Implement akka-apps media permission probes, improve user left and meeting end cleanup triggers
