lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/utils/util.js
Also improved the Kurento adapter error reporting and logging
=> Ignore mDNS candidates for now, added stub to resolve them

lib/mcs-core/lib/media/mcs-message-router.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/model/room.js
Also did some minor standardizing to some logs.
=> Correctly clear rooms when empty and clear floors on ungraceful disconnections

config/default.example.yml, package-lock.json, package.json
Patch release v2.3.3.
*CHANGELOG*:
* Changed the default `packetization-mode` value to `0` in the H.264 media specs config.
=> Version 2.3.3

lib/base/BaseManager.js, lib/base/BaseProvider.js, lib/bbb/messages/Constants.js, lib/bbb/messages/Messaging.js, lib/bbb/messages/stream/StreamOAuth2DataMessage.js, lib/mcs-core/lib/adapters/kurento/kurento.js, lib/oauth2/server.js, lib/stream/StreamManager.js, lib/stream/stream.js, package-lock.json, package.json
Patch release 2.3.4.
_CHANGELOG_:
* Propagate errors from the stream module to clients
* Made sure to always send a response for the stop stream method on the stream module
* Some mild error logging fixes
* Reorganized some of the state fetching in the Kurento adapter to fix some race conditions
=> Version 2.3.4

lib/bbb/messages/Messaging.js, lib/bbb/messages/stream/StreamEventMessage.js, lib/oauth2/server.js, lib/stream/StreamManager.js
Sorry Paolo, before merging we can create a new branch
=> Sending more errors returned from youtube oauth2

config/custom-environment-variables.yml, config/default.example.yml, lib/bbb/messages/Messaging.js, lib/bbb/messages/stream/StreamEventMessage.js, lib/oauth2/server.js, lib/stream/StreamManager.js, package-lock.json, package.json
Patch release 2.3.5.
_CHANGELOG_
* Added default config `bot_name` for the streaming module
* Added more fine-grained errors in the streaming oauth2 procedures
* Added `streamId` to the streaming module `started` message
* Got rid of leftover `console.log` in the streaming module
=> Version 2.3.5

lib/mcs-core/lib/adapters/freeswitch/freeswitch.js
Create the mappings sooner to avoid event sync issue that wrongly created external userAgents/medias
=> Freeswitch channel mappings fix

config/custom-environment-variables.yml, config/default.example.yml, package-lock.json, package.json
Patch release 2.3.7.
__CHANGELOG__
* Change the default recording format to `webm` following the default codec change on v2.3.6.
* Added env. vars to configure the recording format.
=> Version 2.3.7

config/default.example.yml, lib/stream/StreamManager.js, lib/stream/containers/docker.js, lib/stream/containers/kubernetes.js, lib/stream/stream.js
Based on the different types of streams
=> Setting GOP as a variable in the stream containers

config/custom-environment-variables.yml, config/default.example.yml, lib/bbb/pubsub/RedisWrapper.js, lib/connection-manager/HttpServer.js, package-lock.json, package.json
Patch release 2.3.8.
__CHANGELOG__
* Added a new `redisPassword` config option (`REDIS_PASSWORD` env var).
* Added `REDIS_PORT` to the list of configurable env vars.
* Fix a crash caused by unknown and unhandled `HttpServer` errors.
=> Version 2.3.8

lib/mcs-core/lib/adapters/freeswitch/freeswitch.js, lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/media/mcs-message-router.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/model/media-session.js, lib/mcs-core/lib/model/media.js, package-lock.json, package.json
- Closes https://github.com/mconf/bbb-webrtc-sfu/issues/61
- Valid for the Freeswitch adapter. Kurento doesn't support it, so it'll return an appropriate error if somebody tries it.
=> Implement DTMF calls (#61)

lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/media/voice-switching-handler.js, lib/mcs-core/lib/model/room.js
Includes:
- Make the switching algorithm user-aware
- Fix the algorithm for sessions with multiple sink medias
- Fixes to external user handler
=> Improvements to voice-switching-handler

lib/mcs-core/lib/adapters/freeswitch/esl-wrapper.js, lib/mcs-core/lib/adapters/freeswitch/freeswitch.js
And because things are just complicated.
=> DTMF via ESL instead of SIP.js because it is more reliable

config/default.example.yml, lib/mcs-core/lib/utils/logger.js, lib/utils/Logger.js
Addresses #37.
New config option for it: `maxFiles` => number of old log files to keep.
=> Added automatic log file expiry/deletion and config option for it (#37)

lib/mcs-core/lib/adapters/freeswitch/freeswitch.js, lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/constants/constants.js, lib/mcs-core/lib/media/mcs-message-router.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/model/media-session.js, lib/mcs-core/lib/model/media.js, package-lock.json, package.json
=> Implement requestKeyframe/keyframeNeeded (#68)

lib/mcs-core/lib/media/media-controller.js
=> Check if there are new mu-s to index on renegotiations (#86)

lib/screenshare/screenshare.js
Addresses #89 and adds some explanations on why things are like that.
=> [screenshare] Fix #89

lib/audio/audio.js, lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/model/media.js, lib/mcs-core/lib/model/recording-media.js, lib/mcs-core/lib/model/sdp-media.js
Addresses #90. There's one hiccup left due to #88 so it'll be fixed there.
Also, fixed recording offloading when using MEDIA_TYPE balancing (again).
=> Fixed some edge cases with stream counting (#90)

config/default.example.yml, lib/audio/AudioManager.js, lib/audio/audio.js, lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/media/balancer.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/media/media-factory.js, lib/mcs-core/lib/model/media.js, lib/mcs-core/lib/model/recording-media.js, lib/mcs-core/lib/model/sdp-media.js, lib/mcs-core/lib/model/sdp-session.js, lib/mcs-core/lib/utils/base-process.js, lib/mcs-core/lib/utils/sdp-wrapper.js, lib/mcs-core/process.js, lib/screenshare/ScreenshareManager.js, lib/screenshare/screenshare.js, package-lock.json, package.json
Patch release.
__CHANGELOG__
- ** TODO ** :shipit:
=> Version 2.4.1

config/default.example.yml, lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/constants/constants.js, lib/screenshare/screenshare.js, lib/video/VideoManager.js, lib/video/video.js
=> Kurento REMB params made dynamic

.gitignore, config/default.example.yml, lib/mcs-core/lib/adapters/freeswitch/freeswitch.js, lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/constants/constants.js, lib/mcs-core/lib/media/mcs-message-router.js, lib/mcs-core/lib/model/media.js, lib/mcs-core/lib/model/sdp-session.js, lib/oauth2/rnp.js, lib/screenshare/ScreenshareManager.js, lib/screenshare/screenshare.js, lib/stream/containers/docker.js, lib/stream/containers/kubernetes.js, lib/stream/stream.js, lib/video/VideoManager.js, lib/video/video.js, package-lock.json, package.json
=> Version 2.4.3

lib/bbb/messages/Messaging.js, lib/bbb/messages/video/WebRTCShareEvent.js, lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/media/mcs-message-router.js, lib/mcs-core/lib/utils/util.js, lib/screenshare/screenshare.js, lib/video/video.js
Addresses #117 and implement a quick preview of #41.
=> Recording timestamps as the media flow events' timestamps (#117, #41)

lib/audio/AudioManager.js, lib/audio/audio.js, lib/mcs-core/lib/adapters/freeswitch/freeswitch.js, lib/mcs-core/lib/constants/constants.js, lib/mcs-core/lib/media/mcs-message-router.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/model/media.js, lib/mcs-core/lib/model/user.js, lib/screenshare/screenshare.js, lib/video/video.js
This is a bery good steak, best whale steak-e.
Addresses #119 and part of #120.
=> Addresses #119 and part of #120

config/custom-environment-variables.yml, config/default.example.yml, lib/mcs-core/lib/adapters/kurento/kurento.js, package-lock.json, package.json
Patch release 2.4.4.
__CHANGELOG__
- Implemented #109
=>  Addresses #109 and closes 2.4.4

lib/audio/audio.js, lib/screenshare/screenshare.js, lib/utils/Utils.js, lib/video/video.js
Closes #120.
Trying an experiment on #27.
=> Addresses #120, did a mild refactor to provider classes and a log overhaul experiment  with #27

lib/mcs-core/lib/adapters/kurento/kurento.js, package-lock.json, package.json
Also cast ICE candidate dictionaries to the type kurento-client expects.
=> Drop kurento-client-js fork, update to 6.11.0

lib/bbb/pubsub/RedisWrapper.js, lib/bbb/pubsub/bbb-gw.js, lib/oauth2/rnp.js
* Using redis to persist RNP streaming transmissions if the servers shits the bed
* Handling more error codes from RNP
=> Better handling RNP errors and persisting transmissions

lib/mcs-core/lib/model/media-session.js, lib/mcs-core/lib/model/sdp-session.js
Define and parse optional params first in media-session to avoid redefining them.
=> Follow up on #131

Dockerfile, lib/mcs-core/lib/model/media-session.js
Closes #138.
(Also some minor code tidying).
=> Bump Dockerfile's Node.js version to 12 (#138)

lib/mcs-core/lib/adapters/kurento/kurento.js, lib/mcs-core/lib/media/media-controller.js
This avoid error when nesting null promises
Resolves #141
Removed unsed console.log in kurento.js
=> Update leave function's promise

lib/bbb/messages/Constants.js, lib/bbb/pubsub/bbb-gw.js, lib/mcs-core/lib/media/media-controller.js, lib/screenshare/ScreenshareManager.js
This reverts commit 1ec81faa2bc44edcf84388eb9a0067581ea79a27.
=> Revert "Fix content sharing for MCS/RTP users"

lib/bbb/messages/Constants.js, lib/bbb/messages/Messaging.js, lib/bbb/messages/stream/StreamEventMessage.js, lib/oauth2/server.js, lib/stream/StreamManager.js
This could use some good ol' testing. I only compiled in my brains
=> Stream event

config/custom-environment-variables.yml, config/default.example.yml, lib/bbb/messages/OutMessage2x.js, package-lock.json, package.json
Patch release 2.4.5.
__CHANGELOG__:
- Addressed https://github.com/mconf/bbb-webrtc-sfu/issues/151
* Timestamps in akka-apps message envelopes are enabled by default. Can be controlled by `addTimestampToAkkaMessages` (config) or  `AKKA_MSG_TIMESTAMP` (environment variable).
=> Version 2.4.5.

config/custom-environment-variables.yml, config/default.example.yml, lib/mcs-core/lib/adapters/freeswitch/freeswitch.js, lib/mcs-core/lib/model/media.js, lib/mcs-core/lib/model/sdp-media.js, lib/mcs-core/lib/utils/sdp-wrapper.js
Another load testing follow up for 2.4.6 after #159.
- Closes #165 
- Closes #166 
- Closes #167
=> [lt/246-2] Load testing follow-up #2

lib/mcs-core/lib/media/media-controller.js
If there are any content stream when MCU user joins connect it to the new user
Solves #170
=> Connect content stream when MCU users join

lib/mcs-core/lib/adapters/kurento/kurento.js
=> Remove remaning media filters when all MCU participants leave

config/default.example.yml, lib/mcs-core/lib/adapters/freeswitch/freeswitch.js, lib/mcs-core/lib/media/media-controller.js, lib/mcs-core/lib/model/media.js, lib/mcs-core/lib/model/room.js
Addresses:
- mconf#178
- mconf#179
- mconf#180
=> Assorted issues from v2.4.7

lib/mcs-core/lib/constants/constants.js, lib/mcs-core/lib/model/media-session.js
Avoid creating multiple encoders for the same Composite's (MCUSession) video stream
Solves #182
=> Single hubport for MCU video output

lib/mcs-core/lib/model/sdp-session.js, lib/mcs-core/lib/utils/sdp-wrapper.js
=> Increment SDP sess-ver on renegotiations #190

lib/mcs-core/lib/utils/sdp-wrapper.js
=> Trim inactive media lines ( #192)

lib/mcs-core/lib/adapters/kurento/kurento.js, lib/video/VideoManager.js
=> Addresses #197 and #198

lib/stream/StreamManager.js
=> Return after oauth share error

lib/stream/StreamManager.js
This reverts commit 211aab8684aec5e4fc9157648e556658f2a5466e.
I was not actually a dum dum and this return breaks my html5 logic.
=> Revert "Return after oauth share error"

lib/mcs-core/lib/adapters/freeswitch/esl-wrapper.js, package-lock.json, package.json
Closes #92. Also bump `modesl` to v1.2.1.
=> Closes #92 (ESL reconnection procedures).

lib/mcs-core/lib/utils/logger.js, lib/utils/Logger.js
=> Do not colorize stdout logs on production env

lib/mcs-core/lib/utils/sdp-wrapper.js
=> Correctly override SDPs RTCP IN IPx fields (#217)

lib/stream/StreamManager.js, lib/stream/stream.js
Also use streamType as part of streamId
=> Use confname and extId in stream data

lib/video/VideoManager.js, lib/video/video.js
=> Follow up 1 to #242

lib/audio/AudioManager.js, lib/video/VideoManager.js, lib/video/video.js
=> Follow up 2 to #242

config/custom-environment-variables.yml
- Environment value: `BALANCING_STRATEGY`
* Accepted values:  'ROUND_ROBIN' or 'MEDIA_TYPE'
=> Add balancing-strategy env var

lib/screenshare/screenshare.js
-  [screenshare] Add playStart response on media flowing event
-  [screenshare] Fix startViewer error handling
=> [screenshare] Add media flowing server->client event, fix subscribe error handling
